
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: vanel5379
      MYSQL_DATABASE: taskManagement
